# ===================================
#  Form Behavior Config
# ===================================

name: system::lang.mail_templates.template
form: ~/modules/system/models/mailtemplate/fields.yaml
modelClass: System\Models\MailTemplate
defaultRedirect: admin/settings/mailtemplates

create:
    redirect: admin/settings/mailtemplates/update/:id
    redirectClose: admin/settings/mailtemplates

update:
    redirect: admin/settings/mailtemplates
    redirectClose: admin/settings/mailtemplates
