# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.user.name
form: ~/modules/backend/models/user/fields.yaml
modelClass: Backend\Models\User
defaultRedirect: admin/settings/users

create:
    redirect: admin/settings/users/update/:id
    redirectClose: admin/settings/users

update:
    redirect: admin/settings/users
    redirectClose: admin/settings/users
