# ===================================
#  Form Behavior Config
# ===================================

name: system::lang.mail_templates.layout
form: ~/modules/system/models/maillayout/fields.yaml
modelClass: System\Models\MailLayout
defaultRedirect: admin/settings/mailtemplates

create:
    redirect: admin/settings/maillayouts/update/:id
    redirectClose: admin/settings/mailtemplates

update:
    redirect: admin/settings/mailtemplates
    redirectClose: admin/settings/mailtemplates